import {useState,createContext,useContext,useEffect} from 'react'
import {HashRouter,Routes,Route,NavLink,Link,useParams,useNavigate} from 'react-router-dom'
import {LayoutDashboard,Compass,Sparkles,Upload,FileQuestion,Target,Bookmark,User,Search,Bell,BadgeCheck,ThumbsUp,Eye,Share2,Send,Network,FileText,Check,Loader2,Bot,HandHelping,GraduationCap} from 'lucide-react'
import {subjects,units,notes,pyqs,ai,replies} from './data.js'
import {api} from './api.js'

const Ctx=createContext(); const useS=()=>useContext(Ctx)
const card='rounded-2xl border border-white/10 bg-white/[0.03] p-5'
const btn='rounded-xl bg-violet-600 hover:bg-violet-500 px-4 py-2 text-sm font-medium transition'
const ghost='rounded-xl border border-white/10 hover:bg-white/5 px-3 py-2 text-sm transition'
const inp='w-full rounded-xl bg-black/40 border border-white/10 px-3 py-2 text-sm outline-none focus:border-violet-500'
const H=({t,s})=><div className="mb-5"><h1 className="text-2xl font-semibold">{t}</h1>{s&&<p className="text-sm text-zinc-400 mt-1">{s}</p>}</div>
const Badge=({children})=><span className="text-[11px] rounded-full bg-violet-500/15 text-violet-300 px-2 py-0.5">{children}</span>
const USP=()=><div className={card+' glow border-violet-500/30'}><p className="text-zinc-400 text-sm">Existing platforms store files.</p><p className="text-lg font-semibold text-violet-300">We understand, connect and transform them into learning resources.</p><p className="text-xs text-zinc-500 mt-2">Don't just find notes. Find what you need to learn.</p></div>

function NoteCard({n}){const {saved,toggleSave}=useS();const nav=useNavigate();const s=saved.includes(n.id)
return <div className={card+' hover:border-violet-500/40 transition flex flex-col gap-2'}>
<div className="flex gap-2 flex-wrap"><Badge>{n.type}</Badge>{n.verified&&<span className="text-[11px] text-emerald-400 flex items-center gap-1"><BadgeCheck size={13}/>Verified Academic Resource</span>}</div>
<h3 className="font-medium leading-snug">{n.title}</h3>
<p className="text-xs text-zinc-400">{n.subj} · {n.unit} · {n.topic}</p>
<p className="text-xs text-zinc-500">By {n.by} · <ThumbsUp size={11} className="inline"/> {n.helpful}% helpful · <Eye size={11} className="inline"/> {n.views}</p>
<div className="flex gap-2 mt-auto pt-2"><button className={btn} onClick={()=>nav('/note/'+n.id)}>Preview</button><button className={ghost+(s?' text-violet-300 border-violet-500':'')} onClick={()=>toggleSave(n.id)}><Bookmark size={14} className="inline mr-1" fill={s?'currentColor':'none'}/>{s?'Saved':'Save'}</button></div></div>}

function Login({go}){return <div className="min-h-screen grid place-items-center p-4"><div className="w-full max-w-md"><div className="text-center mb-6"><div className="inline-grid place-items-center size-12 rounded-2xl bg-violet-600 glow mb-3"><GraduationCap/></div><h1 className="text-3xl font-bold">Pragya</h1><p className="text-zinc-400 text-sm">AI-Powered Collaborative Academic Knowledge Platform</p></div>
<div className={card+' space-y-3'}><input className={inp} placeholder="College email" defaultValue="prathmesh@aiml.edu"/><input className={inp} type="password" placeholder="Password" defaultValue="demo1234"/><button className={btn+' w-full'} onClick={go}>Log in</button><button className={ghost+' w-full'} onClick={go}>Sign up</button><button className="w-full text-violet-300 text-sm py-1" onClick={go}>Continue as Demo Student →</button></div>
<div className="mt-4"><USP/></div></div></div>}

function Dashboard(){const {saved,helpful,uploads}=useS()
return <div className="space-y-5"><div><h1 className="text-2xl font-semibold">Good morning, Prathmesh 👋</h1><div className="flex gap-2 mt-2 flex-wrap"><Badge>AIML</Badge><Badge>Semester 2</Badge><Badge>SPPU</Badge><Badge>AY 2025–26</Badge></div></div><USP/>
<div className="grid md:grid-cols-2 gap-4"><div className={card}><p className="text-xs text-zinc-400">Continue Learning</p><h3 className="font-medium mt-1">Object Oriented Programming</h3><div className="h-2 rounded bg-white/10 mt-3"><div className="h-2 rounded bg-violet-500 w-[72%]"/></div><p className="text-xs text-zinc-400 mt-1">72% · Next: Unit 3 Polymorphism</p></div>
<div className={card}><p className="text-xs text-zinc-400">Upcoming Exam</p><h3 className="font-medium mt-1">Data Structures</h3><p className="text-3xl font-bold text-violet-300 mt-2">12 <span className="text-sm text-zinc-400 font-normal">days remaining</span></p></div></div>
<div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[['/upload','Upload Notes',Upload],['/search','Search Notes',Search],['/ai','Ask AI',Bot],['/exam','Exam Mode',Target]].map(([to,l,I])=><Link key={l} to={to} className={card+' hover:border-violet-500/50 flex items-center gap-2 text-sm'}><I size={18} className="text-violet-400"/>{l}</Link>)}</div>
<div><h2 className="font-medium mb-3">Recommended for you</h2><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{notes.slice(0,3).map(n=><NoteCard key={n.id} n={n}/>)}</div></div>
<div className="grid md:grid-cols-2 gap-4"><div className={card}><h3 className="font-medium mb-2">Recent activity</h3>{['You marked "Normalization" helpful','Ananya uploaded Binary Trees notes','23 students requested DBMS Unit 4','Your note was verified ✓'].map(a=><p key={a} className="text-sm text-zinc-400 py-1 border-b border-white/5">{a}</p>)}<p className="text-xs text-zinc-500 mt-2">Saved: {saved.length} · Helpful votes: {helpful} · Uploads: {uploads}</p></div>
<div className={card}><h3 className="font-medium mb-2 flex items-center gap-2"><Sparkles size={16} className="text-violet-400"/>Personalized</h3>{['Polymorphism is asked in 3/3 recent PYQs — revise it first','You haven\'t opened Exception Handling yet','Take the Unit 3 MCQ quiz to find weak topics'].map(a=><p key={a} className="text-sm text-zinc-300 py-1.5">• {a}</p>)}</div></div></div>}

const syn={'polymorph':'polymorphism','many forms':'polymorphism','override':'overriding','overload':'overloading','tree':'tree','normal':'normalization','search':'search','exception':'exception','error':'exception'}
function SearchPg(){const [q,setQ]=useState('Explain polymorphism with a Java example');const [f,setF]=useState({subj:'',type:''});const [go,setGo]=useState(true)
const [res,setRes]=useState([]);useEffect(()=>{const t=setTimeout(()=>api.search(q,f).then(setRes),250);return()=>clearTimeout(t)},[q,f])
return <div><H t="Semantic Search" s="Search by meaning, not filenames."/>
<div className="flex gap-2"><input className={inp+' text-base py-3'} value={q} onChange={e=>{setQ(e.target.value);setGo(true)}} placeholder="Search anything you need to learn…"/><button className={btn} onClick={()=>setGo(true)}><Search size={16}/></button></div>
<div className="flex gap-2 mt-3 flex-wrap"><select className={inp+' !w-auto'} onChange={e=>setF({...f,subj:e.target.value})}><option value="">All subjects</option>{subjects.map(s=><option key={s}>{s}</option>)}</select><select className={inp+' !w-auto'} onChange={e=>setF({...f,type:e.target.value})}><option value="">All resource types</option>{['Study Notes','PYQ','Handwritten','Faculty Material'].map(s=><option key={s}>{s}</option>)}</select><select className={inp+' !w-auto'}><option>Semester 2</option><option>Semester 1</option></select><select className={inp+' !w-auto'}><option>2025</option><option>2024</option></select></div>
<div className="grid lg:grid-cols-3 gap-4 mt-5"><div className="lg:col-span-2 space-y-3">{res.length===0&&<p className="text-zinc-400">No semantic matches. Try "overriding", "trees", "normalization"…</p>}{res.map(n=><Link to={'/note/'+n.id} key={n.id} className={card+' block hover:border-violet-500/50'}><div className="flex justify-between gap-3"><div><h3 className="font-medium">{n.title}</h3><p className="text-xs text-zinc-400 mt-1">{n.subj} · {n.unit} · {n.topic} · {n.type}</p></div><div className="text-right shrink-0"><p className="text-xl font-bold text-violet-300">{Math.round(n.score)}%</p><p className="text-[10px] text-zinc-500">semantic match</p></div></div><div className="h-1 rounded bg-white/10 mt-3"><div className="h-1 rounded bg-violet-500" style={{width:n.score+'%'}}/></div></Link>)}</div>
<div className={card+' h-fit text-sm'}><h3 className="font-medium mb-3">Why this beats filename search</h3><p className="text-zinc-400">Filename search for "<span className="text-white">{q}</span>" finds:</p><p className="text-red-400 my-2">✗ 0 files named like that</p><p className="text-zinc-400">Pragya understands the <span className="text-violet-300">concept</span>, maps it to the syllabus and returns notes, PYQs and revision sheets — even when the title never mentions your words.</p></div></div></div>}

function Explore(){const [sub,setSub]=useState('Object Oriented Programming');const [u,setU]=useState(null)
const list=notes.filter(n=>n.subj===sub&&(!u||u.startsWith(n.unit)))
return <div><H t="Explore Notes" s="Semester 2 → Subject → Unit → Topic"/><div className="flex gap-2 flex-wrap mb-3">{subjects.map(s=><button key={s} onClick={()=>{setSub(s);setU(null)}} className={ghost+(s===sub?' !border-violet-500 text-violet-300':'')}>{s}</button>)}</div>
<div className="flex gap-2 flex-wrap mb-5">{units[sub].map(x=><button key={x} onClick={()=>setU(u===x?null:x)} className={'text-xs rounded-full px-3 py-1 border '+(u===x?'border-violet-500 bg-violet-500/20':'border-white/10 text-zinc-400')}>{x}</button>)}</div>
<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{list.map(n=><NoteCard key={n.id} n={n}/>)}{!list.length&&<p className="text-zinc-400 text-sm">No notes yet for this unit. <Link className="text-violet-300" to="/request">Request a note →</Link></p>}</div></div>}

function NoteDetail(){const {id}=useParams();const n=notes.find(x=>x.id==id)||notes[0];const {saved,toggleSave,helpful,voteHelpful}=useS();const [tab,setTab]=useState('Summary');const [ans,setAns]=useState({});const [chat,setChat]=useState([]);const [msg,setMsg]=useState('')
const tabs=['Summary','Key Concepts','Important Questions','MCQs','Ask This Note']
const send=()=>{if(!msg)return;setChat(c=>[...c,['u',msg],['a','Think of it like a remote control: the same "press play" button works differently on a TV or a speaker — one interface, many behaviours. That is polymorphism. (Source: '+n.title+', p.3)']]);setMsg('')}
return <div className="grid lg:grid-cols-2 gap-5"><div className={card+' min-h-[420px]'}><div className="flex items-center gap-2 text-sm text-zinc-400 mb-3"><FileText size={16}/>{n.title}.pdf · 12 pages</div>{n.file?<FileView f={n.file}/>:<div className="rounded-xl bg-white text-zinc-800 p-6 text-sm space-y-2 font-serif"><h3 className="font-bold text-lg">{n.topic}</h3><p>Polymorphism = "many forms". In Java it is achieved in two ways:</p><p>1. Compile-time (method overloading)<br/>2. Run-time (method overriding)</p><pre className="bg-zinc-100 p-3 rounded text-xs">{`class Animal { void sound(){ } }\nclass Dog extends Animal {\n  @Override void sound(){ print("Bark"); }\n}\nAnimal a = new Dog(); a.sound();`}</pre><p className="text-zinc-500 text-xs">… page 1 of 12</p></div>}</div>
<div className="space-y-4"><div className={card}><div className="flex gap-2 items-center flex-wrap"><Badge>{n.subj}</Badge><Badge>{n.unit}</Badge><Badge>{n.topic}</Badge>{n.verified&&<span className="text-emerald-400 text-xs flex gap-1"><BadgeCheck size={14}/>Verified</span>}</div><h1 className="text-xl font-semibold mt-3">{n.title}</h1><p className="text-xs text-zinc-400 mt-1">Uploaded by {n.by} · v3 (version history) · {n.helpful}% helpful</p>
<div className="flex gap-2 mt-3"><button className={btn} onClick={voteHelpful}><ThumbsUp size={14} className="inline mr-1"/>Helpful ({helpful})</button><button className={ghost} onClick={()=>toggleSave(n.id)}><Bookmark size={14} className="inline mr-1"/>{saved.includes(n.id)?'Saved':'Save'}</button><button className={ghost} onClick={()=>navigator.clipboard?.writeText(location.href)}><Share2 size={14} className="inline mr-1"/>Share</button></div></div>
<div className={card+' border-violet-500/30'}><h3 className="font-medium flex items-center gap-2 mb-3"><Sparkles size={16} className="text-violet-400"/>AI Notes Intelligence</h3><div className="flex gap-1 flex-wrap mb-4">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={'text-xs px-3 py-1.5 rounded-lg '+(tab===t?'bg-violet-600':'bg-white/5 text-zinc-400')}>{t}</button>)}</div>
{tab==='Summary'&&<p className="text-sm text-zinc-300 leading-relaxed">{ai.summary}</p>}
{tab==='Key Concepts'&&<div className="flex flex-wrap gap-2">{ai.concepts.map(c=><span key={c} className="text-sm rounded-lg bg-violet-500/10 border border-violet-500/30 px-3 py-1.5">{c}</span>)}</div>}
{tab==='Important Questions'&&<ol className="text-sm space-y-2 text-zinc-300 list-decimal pl-5">{ai.qs.map(q=><li key={q}>{q}</li>)}<li><Link className="text-violet-300" to="/pyqs">See PYQ history →</Link></li></ol>}
{tab==='MCQs'&&<div className="space-y-4">{ai.mcq.map((m,i)=><div key={i}><p className="text-sm mb-2">{i+1}. {m.q}</p><div className="grid grid-cols-2 gap-2">{m.o.map((o,j)=>{const a=ans[i];const c=a!==undefined&&(j===m.a?'border-emerald-500 bg-emerald-500/10':j===a?'border-red-500 bg-red-500/10':'');return <button key={j} onClick={()=>ans[i]===undefined&&setAns({...ans,[i]:j})} className={'text-xs text-left rounded-lg border border-white/10 px-3 py-2 '+c}>{o}</button>})}</div></div>)}</div>}
{tab==='Ask This Note'&&<div><div className="space-y-2 mb-3 max-h-48 overflow-auto">{chat.map(([r,t],i)=><p key={i} className={'text-sm rounded-xl px-3 py-2 '+(r==='u'?'bg-violet-600 ml-8':'bg-white/5 mr-8')}>{t}</p>)}</div><div className="flex gap-2"><input className={inp} value={msg} onChange={e=>setMsg(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Explain this topic like I'm a beginner."/><button className={btn} onClick={send}><Send size={14}/></button></div></div>}</div></div></div>}

const stages=['Uploading','OCR / Text Extraction','AI Processing','Syllabus Mapping','Ready']
function UploadPg(){const {reload}=useS();const [st,setSt]=useState(-1);const [kind,setKind]=useState('Study Notes');const [file,setFile]=useState(null);const [drag,setDrag]=useState(false);const [err,setErr]=useState('');const [m,setM]=useState({title:'',subj:subjects[0],unit:'',topic:'',description:''})
const set=k=>e=>setM({...m,[k]:e.target.value})
const start=async()=>{if(!file)return setErr('Choose a file first');if(!m.title)return setErr('Add a title');setErr('');setSt(0);const fd=new FormData();fd.append('file',file);Object.entries({...m,unit:m.unit.split(':')[0],type:kind}).forEach(([k,v])=>fd.append(k,v));const r=await api.upload(fd);if(!r){setErr('Upload failed — is the backend running?');setSt(-1);return}reload()}
const reset=()=>{setSt(-1);setFile(null);setM({...m,title:'',topic:'',description:''})}
useEffect(()=>{if(st<0||st>=4)return;const t=setTimeout(()=>setSt(st+1),700);return()=>clearTimeout(t)},[st])
return <div><H t="Upload Notes" s="Upload once. Pragya understands, maps and connects it."/>
<div className="grid lg:grid-cols-2 gap-5"><div className={card+' space-y-3'}><label onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);setFile(e.dataTransfer.files[0])}} className={'block cursor-pointer border-2 border-dashed rounded-2xl p-8 text-center '+(drag?'border-violet-400 bg-violet-500/10':'border-violet-500/40')}><input type="file" hidden accept=".pdf,.doc,.docx,image/*" onChange={e=>setFile(e.target.files[0])}/><Upload className="mx-auto text-violet-400 mb-2"/><p className="font-medium">{file?file.name:'Upload your academic notes'}</p><p className="text-xs text-zinc-500">{file?(file.size/1024).toFixed(0)+' KB · click to change':'Drag & drop or click · PDF · DOCX · Images · Handwritten'}</p></label>
<input className={inp} placeholder="Title *" value={m.title} onChange={set('title')}/>
<div className="grid grid-cols-2 gap-2"><select className={inp}><option>Semester 2</option><option>Semester 1</option></select><select className={inp} value={m.subj} onChange={e=>setM({...m,subj:e.target.value,unit:''})}>{subjects.map(s=><option key={s}>{s}</option>)}</select><select className={inp} value={m.unit} onChange={set('unit')}><option value="">Select unit</option>{units[m.subj].map(x=><option key={x}>{x}</option>)}</select><input className={inp} placeholder="Topic" value={m.topic} onChange={set('topic')}/></div>
<textarea className={inp} rows={2} placeholder="Description" value={m.description} onChange={set('description')}/>
<div className="flex flex-wrap gap-2">{[['Handwritten','Handwritten notes'],['PYQ','Previous year question paper'],['Study Notes','Study notes'],['Faculty Material','Faculty material']].map(([v,l])=><button key={v} onClick={()=>setKind(v)} className={'text-xs rounded-full px-3 py-1 border '+(kind===v?'border-violet-500 bg-violet-500/20':'border-white/10 text-zinc-400')}>{l}</button>)}</div>
{err&&<p className="text-sm text-red-400">{err}</p>}<button className={btn+' w-full disabled:opacity-50'} disabled={st>=0&&st<4} onClick={start}>Upload & Process</button></div>
<div className={card}><h3 className="font-medium mb-3">AI pipeline</h3>{stages.map((s,i)=><div key={s} className="flex items-center gap-3 py-2">{i<st||st===4?<Check size={16} className="text-emerald-400"/>:i===st?<Loader2 size={16} className="animate-spin text-violet-400"/>:<span className="size-4 rounded-full border border-white/20"/>}<span className={'text-sm '+(i<=st?'text-white':'text-zinc-500')}>{s}</span></div>)}
{st===4&&<div className="mt-3 rounded-xl bg-emerald-500/10 border border-emerald-500/30 p-3 text-sm space-y-1">{['Text extracted','Topic detected: Polymorphism','Syllabus matched: OOP → Unit 3','AI summary generated','Duplicate check completed'].map(x=><p key={x}>✓ {x}</p>)}<div className="flex gap-2 pt-2"><Link to="/my" className={btn}>View in My Notes</Link><button className={ghost} onClick={reset}>Upload another</button></div></div>}</div></div>
<div className={card+' mt-5'}><h3 className="font-medium mb-1">Handwritten → Digital</h3><p className="text-xs text-zinc-400 mb-4">Not just OCR — the full academic processing pipeline.</p><div className="flex flex-wrap gap-2 text-xs mb-4">{['Handwritten Image','OCR','Structured Text','Topic Detection','Syllabus Mapping','Searchable Notes'].map((x,i,a)=><span key={x} className="flex items-center gap-2"><span className="rounded-lg bg-violet-500/15 px-2 py-1">{x}</span>{i<a.length-1&&'→'}</span>)}</div>
<div className="grid md:grid-cols-2 gap-4"><div className="rounded-xl bg-amber-50 text-zinc-700 p-4 italic h-40 -rotate-1" style={{fontFamily:'cursive'}}>Polymorphism – many forms<br/>1) Overloading → same name, diff params<br/>2) Overriding → child changes parent method</div><div className="rounded-xl bg-black/40 border border-white/10 p-4 text-sm"><p className="text-emerald-400 text-xs mb-1">Extracted • 97% confidence</p><p className="font-medium">## Polymorphism</p><p className="text-zinc-300">- Overloading: same name, different parameters</p><p className="text-zinc-300">- Overriding: subclass redefines parent method</p><p className="text-violet-300 text-xs mt-2">Mapped → OOP · Unit 3 · Polymorphism</p></div></div></div></div>}

function PYQ(){const [subj,setSubj]=useState(subjects[0]);const [list,setList]=useState(null);const [top,setTop]=useState('');const [err,setErr]=useState(false)
useEffect(()=>{setList(null);setErr(false);api.pyqs(subj).then(r=>{if(!r)return setErr(true);setList(r);setTop(r[0]?.topic||'')})},[subj])
const t=list?.find(x=>x.topic===top);const rel=t?notes.filter(n=>n.subj===subj&&n.topic===t.topic):[];const max=t?Math.max(...t.asked.map(a=>a.marks)):1
return <div><H t="PYQ Intelligence" s="Notes ↔ PYQs ↔ Important Questions ↔ Revision, per topic"/>
<div className="flex gap-2 mb-3 flex-wrap">{subjects.map(x=><button key={x} onClick={()=>setSubj(x)} className={ghost+(x===subj?' !border-violet-500 text-violet-300':'')}>{x}</button>)}</div>
{err&&<p className="text-sm text-red-400">Could not reach the backend — is it running?</p>}
{list&&!list.length&&<p className="text-sm text-zinc-400">No PYQs for this subject yet.</p>}
{list&&list.length>0&&<><div className="flex gap-2 mb-4 flex-wrap">{list.map(x=><button key={x.topic} onClick={()=>setTop(x.topic)} className={'text-xs rounded-full px-3 py-1 border '+(x.topic===top?'border-violet-500 bg-violet-500/20':'border-white/10 text-zinc-400')}>{x.topic} · {x.freq}×</button>)}</div>
{t&&<div className={card+' space-y-4'}><div className="flex items-center gap-2 flex-wrap"><h2 className="text-lg font-medium">{t.topic}</h2><Badge>{t.unit}</Badge>{t.freq>=3?<Badge>🔥 Frequently Asked Topic</Badge>:<Badge>Asked in {t.freq} paper{t.freq>1?'s':''}</Badge>}<span className="text-xs text-zinc-400">{t.marks} total marks</span></div>
<div className="space-y-2">{t.asked.map((a,i)=><div key={i} className="rounded-xl bg-white/5 p-3"><p className="text-sm text-zinc-200">"{a.question}"</p><div className="flex items-center gap-2 mt-2 text-xs text-zinc-400"><span className="w-10">{a.year}</span><div className="h-1.5 flex-1 rounded bg-white/10"><div className="h-1.5 rounded bg-violet-500" style={{width:(a.marks/max*100)+'%'}}/></div><span>{a.marks} marks</span></div></div>)}</div>
<div className="grid grid-cols-2 md:grid-cols-4 gap-2 text-sm text-center">{[[rel[0]?'/note/'+rel[0].id:'/request','Notes ('+rel.length+')'],['/pyqs','PYQs ('+t.freq+')'],['/ai','Important Questions'],['/exam','Revision']].map(([to,l])=><Link key={l} to={to} className="rounded-xl border border-violet-500/30 bg-violet-500/10 py-3 hover:bg-violet-500/20">{l}</Link>)}</div>
<div><p className="text-xs text-zinc-400 mb-2">Connected notes</p>{rel.length?<div className="grid md:grid-cols-2 gap-3">{rel.map(n=><NoteCard key={n.id} n={n}/>)}</div>:<p className="text-sm text-zinc-400">No notes for this topic yet. <Link className="text-amber-400" to="/request">Request one →</Link></p>}</div></div>}</>}</div>}

function Exam(){const [subj,setSubj]=useState(subjects[0]);const [d,setD]=useState(3);const [data,setData]=useState(null);const [busy,setBusy]=useState(false);const [err,setErr]=useState('')
const gen=async()=>{setBusy(true);setErr('');const r=await api.plan(subj,d);setBusy(false);if(!r)return setErr('Could not reach the backend — is it running?');setData(r)}
const tog=async t=>{await api.progress(subj,t);gen()}
const col={HIGH:'text-red-400',MEDIUM:'text-amber-400',LOW:'text-emerald-400'}
return <div><H t="Prepare for your exam" s="Plan built from PYQ history, available notes and your progress"/>
<div className={card+' flex gap-3 flex-wrap items-end'}><div><p className="text-xs text-zinc-400 mb-1">Exam</p><select className={inp} value={subj} onChange={e=>{setSubj(e.target.value);setData(null)}}>{subjects.map(x=><option key={x}>{x}</option>)}</select></div><div><p className="text-xs text-zinc-400 mb-1">Days remaining</p><input type="number" min={1} max={14} className={inp+' !w-24'} value={d} onChange={e=>setD(+e.target.value)}/></div><button className={btn} onClick={gen} disabled={busy}><Sparkles size={14} className="inline mr-1"/>{busy?'Analysing…':'Generate Preparation Plan'}</button></div>
{err&&<p className="text-sm text-red-400 mt-3">{err}</p>}
{data&&<div className="mt-5 space-y-5"><div className="grid md:grid-cols-3 gap-4">{['HIGH','MEDIUM','LOW'].map(p=><div key={p} className={card}><p className={'text-xs font-semibold '+col[p]}>{p} PRIORITY</p>{data.topics.filter(x=>x.priority===p).map(x=><div key={x.topic} className="mt-3 text-sm"><div className="flex justify-between gap-2"><span className={x.done?'line-through text-zinc-500':''}>{x.topic}</span><button onClick={()=>tog(x.topic)} className="text-[11px] text-violet-300 shrink-0">{x.done?'Undo':'Mark studied'}</button></div><p className="text-xs text-zinc-500">{x.freq?'asked '+x.freq+'× · '+x.marks+' marks':'not asked recently'} · {x.notes.length?x.notes.length+' note(s)':'no notes yet'}</p>{x.notes[0]&&<Link to={'/note/'+x.notes[0].id} className="text-xs text-violet-300">Open note →</Link>}{!x.notes.length&&<Link to="/request" className="text-xs text-amber-400">Request a note →</Link>}</div>)}</div>)}</div>
<div className="grid md:grid-cols-3 gap-4">{data.plan.map(x=><div key={x.day} className={card}><p className="font-medium text-violet-300 mb-2">Day {x.day} — {x.title}</p>{x.items.map((y,i)=><p key={i} className="text-sm text-zinc-300 mb-1">→ {y}</p>)}</div>)}</div>
<div className={card}><p className="font-medium mb-2">Why these topics?</p><div className="grid grid-cols-2 md:grid-cols-4 gap-2 text-xs">{[['Syllabus',data.why.topics+' topics in '+data.subj],['PYQ frequency',data.why.pyqs+' past questions analysed'],['Available notes',data.why.notes+' notes · '+data.why.gaps+' topic(s) without notes'],['Your progress',data.why.studied+' of '+data.why.topics+' topics studied']].map(([a,b])=><div key={a} className="rounded-lg bg-white/5 p-3"><p className="text-violet-300">{a}</p><p className="text-zinc-400 mt-1">{b}</p></div>)}</div></div></div>}</div>}

function Assistant(){const [m,setM]=useState([['a','Hi Prathmesh! I answer using notes, PYQs and syllabus on Pragya.']]);const [v,setV]=useState('')
const ask=t=>{if(!t)return;const l=t.toLowerCase();const r=l.includes('inherit')?replies.inherit:l.includes('question')?replies.question:l.includes('plan')?replies.plan:l.includes('note')?replies.note:replies.def;setM(x=>[...x,['u',t],['a',r]]);setV('')}
return <div><H t="Pragya AI" s="Answers grounded in platform resources"/><div className={card}><div className="space-y-3 min-h-[260px] max-h-[420px] overflow-auto">{m.map(([r,t],i)=><div key={i} className={r==='u'?'ml-12':'mr-12'}><p className={'text-sm rounded-xl px-3 py-2 '+(r==='u'?'bg-violet-600':'bg-white/5')}>{t}</p>{r==='a'&&i>0&&<div className="flex gap-1 mt-1">{['OOP Unit 3 Notes','PYQ 2025'].map(s=><span key={s} className="text-[10px] text-violet-300 bg-violet-500/10 rounded px-2 py-0.5">📎 {s}</span>)}</div>}</div>)}</div>
<div className="flex gap-2 flex-wrap my-3">{['Explain inheritance simply','Give me important OOP questions','Create a 2-day revision plan','Explain this note'].map(q=><button key={q} className="text-xs rounded-full border border-white/10 px-3 py-1 text-zinc-300 hover:border-violet-500" onClick={()=>ask(q)}>{q}</button>)}</div>
<div className="flex gap-2"><input className={inp} value={v} onChange={e=>setV(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask(v)} placeholder="Ask Pragya AI…"/><button className={btn} onClick={()=>ask(v)}><Send size={14}/></button></div></div></div>}

const TI={'Polymorphism':{c:['Overloading','Overriding','Dynamic dispatch'],pyq:'2025 · 8 marks',q:3},'Method Overriding':{c:['@Override','super keyword','Covariant return'],pyq:'2024 · 6 marks',q:2},'Exception Handling':{c:['try / catch','finally','throw vs throws'],pyq:'2024 · 8 marks',q:3},'Trees':{c:['Inorder / Preorder','BST','Tree height'],pyq:'2025 · 6 marks',q:3},'Normalization':{c:['1NF / 2NF / 3NF','BCNF','Functional dependency'],pyq:'2025 · 8 marks',q:4},'Search':{c:['BFS / DFS','A* heuristic','Agent types'],pyq:'2024 · 6 marks',q:2}}
const E=[[0,1],[1,2],[2,3],[3,4],[3,5],[3,6],[4,7],[5,7],[6,8],[5,8]]
const ab=x=>x.split(' ').filter(w=>w[0]===w[0].toUpperCase()).map(w=>w[0]).join('')
function Graph(){const subs=subjects.filter(x=>notes.some(n=>n.subj===x));const [sub,setSub]=useState(subs[0]);const [top,setTop]=useState('');const [s,setS]=useState(3)
const topics=[...new Set(notes.filter(n=>n.subj===sub).map(n=>n.topic))];const t=topics.includes(top)?top:topics[0]
const tn=notes.filter(n=>n.subj===sub&&n.topic===t);const info=TI[t]||{c:['Core concept','Definition','Worked example'],pyq:'2025 · 6 marks',q:2};const py=pyqs.find(p=>p.topic===t)
const un=tn[0]?.unit||'';const unFull=(units[sub]||[]).find(x=>x.startsWith(un))||un
const N=[['Syllabus',300,30,'AIML Semester 2 · SPPU'],[ab(sub),300,100,sub+' — '+(units[sub]||[]).length+' units'],[un,300,170,unFull],[t.length>12?t.slice(0,11)+'…':t,300,240,'Topic: '+t+' — '+(py?'asked in '+py.asked.length+' recent papers':'frequently revised')],['Notes ('+tn.length+')',130,330,tn.length+' note(s) mapped to this topic'],['PYQ',300,330,py?py.q+' ('+py.asked.map(a=>a[0]+' — '+a[1]+'m').join(', ')+')':'Last asked: '+info.pyq],['Concepts',470,330,info.c.join(' · ')],['Imp. Questions',215,410,info.q+' AI-generated important questions from PYQs + notes'],['Revision',385,410,'1-page revision sheet + MCQ quiz for '+t]]
return <div><H t="Knowledge Graph" s="Syllabus → Subject → Unit → Topic → Notes, PYQs, Concepts. Pick a subject and topic, then click a node."/>
<div className="flex gap-2 flex-wrap mb-2">{subs.map(x=><button key={x} onClick={()=>{setSub(x);setTop('');setS(3)}} className={ghost+(x===sub?' !border-violet-500 text-violet-300':'')}>{x}</button>)}</div>
<div className="flex gap-2 flex-wrap mb-4">{topics.map(x=><button key={x} onClick={()=>{setTop(x);setS(3)}} className={'text-xs rounded-full px-3 py-1 border '+(x===t?'border-violet-500 bg-violet-500/20':'border-white/10 text-zinc-400')}>{x}</button>)}</div>
<div className={card+' grid lg:grid-cols-3 gap-4'}><svg viewBox="0 0 600 450" className="lg:col-span-2 w-full">{E.map(([a,b],i)=><line key={i} x1={N[a][1]} y1={N[a][2]} x2={N[b][1]} y2={N[b][2]} stroke={a===s||b===s?'#a78bfa':'#3f3f46'} strokeWidth="1.5"/>)}{N.map(([l,x,y],i)=><g key={i} onClick={()=>setS(i)} className="cursor-pointer"><circle cx={x} cy={y} r={i===s?30:24} fill={i===s?'#7c3aed':'#18181b'} stroke="#8b5cf6" strokeWidth="1.5"/><text x={x} y={y+4} textAnchor="middle" fontSize="9" fill="#fff">{l}</text></g>)}</svg>
<div className="rounded-xl bg-white/5 p-4 h-fit"><p className="text-violet-300 font-medium">{N[s][0]}</p><p className="text-sm text-zinc-300 mt-2">{N[s][3]}</p>{s===4&&tn.map(n=><Link key={n.id} to={'/note/'+n.id} className="block text-sm text-violet-300 mt-2 underline">{n.title}</Link>)}{s===5&&<Link to="/pyqs" className="block text-sm text-violet-300 mt-2 underline">Open PYQ intelligence →</Link>}<p className="text-xs text-zinc-500 mt-3">Connected to: {E.filter(e=>e.includes(s)).map(e=>N[e[0]===s?e[1]:e[0]][0]).join(', ')}</p></div></div></div>}

function Request(){const [n,setN]=useState(23);const [d,setD]=useState(false);const [t,setT]=useState('Need handwritten notes for DBMS Unit 4.');return <div><H t="Request a Note" s="Can't find what you need?"/><div className={card+' max-w-xl space-y-3'}><select className={inp}>{subjects.map(s=><option key={s}>{s}</option>)}</select><input className={inp} placeholder="Unit" defaultValue="Unit 4"/><input className={inp} placeholder="Topic" defaultValue="Transactions & Concurrency"/><textarea className={inp} value={t} onChange={e=>setT(e.target.value)} rows={2}/>
<button className={btn} onClick={()=>{if(!d){setN(n+1);setD(true);api.request({description:t}).then(r=>r&&setN(r.count))}}}>{d?'Request submitted ✓':'Submit request'}</button><p className="text-sm text-violet-300"><HandHelping size={14} className="inline mr-1"/>{n} students are looking for this.</p></div></div>}

function Profile(){const {helpful,uploads,saved}=useS();return <div><H t="Profile"/><div className="grid md:grid-cols-3 gap-4"><div className={card+' text-center'}><div className="size-16 rounded-full bg-violet-600 grid place-items-center text-xl mx-auto">P</div><p className="font-medium mt-2">Prathmesh</p><p className="text-xs text-zinc-400">AIML · Sem 2 · SPPU</p><p className="text-4xl font-bold text-violet-300 mt-3">4.8<span className="text-sm text-zinc-400"> / 5</span></p><p className="text-xs text-zinc-400">Academic Contributor Score</p></div>
<div className={card+' md:col-span-2 grid grid-cols-2 gap-3'}>{[['Resources Uploaded',24+uploads],['Helpful Votes',186+helpful-142],['Verified Resources',12],['Saved Resources',saved.length]].map(([a,b])=><div key={a} className="rounded-xl bg-white/5 p-4"><p className="text-2xl font-semibold">{b}</p><p className="text-xs text-zinc-400">{a}</p></div>)}</div></div>
<div className={card+' mt-4 flex items-center gap-3'}><div className="size-10 rounded-full bg-fuchsia-600 grid place-items-center">A</div><div><p className="font-medium">Ananya Sharma <BadgeCheck size={14} className="inline text-emerald-400"/></p><p className="text-xs text-zinc-400">Academic Contributor · ⭐ 4.8 · 124 Helpful Votes · 32 Resources</p></div></div></div>}

function Saved(){const {saved}=useS();const l=notes.filter(n=>saved.includes(n.id));return <div><H t="Saved"/><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{l.map(n=><NoteCard key={n.id} n={n}/>)}{!l.length&&<p className="text-zinc-400 text-sm">Nothing saved yet — save notes from Explore.</p>}</div></div>}

function FileView({f}){const u=api.fileUrl(f);return /\.(png|jpe?g|gif|webp)$/i.test(f)?<img src={u} className="rounded-xl w-full"/>:/\.pdf$/i.test(f)?<iframe src={u} className="w-full h-[480px] rounded-xl bg-white"/>:<a href={u} target="_blank" className={btn+' inline-block'}>Download file</a>}
function MyNotes(){const {reload}=useS();const [ed,setEd]=useState(null);const mine=notes.filter(n=>n.by==='Prathmesh')
const del=async n=>{if(confirm('Delete "'+n.title+'"?')){await api.del(n.id);reload()}}
const save=async()=>{await api.edit(ed.id,ed);setEd(null);reload()}
return <div><H t="My Notes" s="Notes you uploaded — edit or delete them."/><div className="space-y-3">{mine.map(n=><div key={n.id} className={card+' flex flex-wrap items-center gap-3'}>
{ed?.id===n.id?<div className="flex-1 grid md:grid-cols-2 gap-2 min-w-[260px]"><input className={inp} value={ed.title} onChange={e=>setEd({...ed,title:e.target.value})}/><input className={inp} value={ed.topic} onChange={e=>setEd({...ed,topic:e.target.value})}/><select className={inp} value={ed.subj} onChange={e=>setEd({...ed,subj:e.target.value})}>{subjects.map(s=><option key={s}>{s}</option>)}</select><input className={inp} value={ed.unit} onChange={e=>setEd({...ed,unit:e.target.value})}/></div>
:<Link to={'/note/'+n.id} className="flex-1 min-w-[200px]"><p className="font-medium">{n.title}</p><p className="text-xs text-zinc-400">{n.subj} · {n.unit} · {n.topic} · {n.type}</p></Link>}
{ed?.id===n.id?<><button className={btn} onClick={save}>Save</button><button className={ghost} onClick={()=>setEd(null)}>Cancel</button></>:<><button className={ghost} onClick={()=>setEd({...n})}>Edit</button><button className={ghost+' text-red-400'} onClick={()=>del(n)}>Delete</button></>}</div>)}
{!mine.length&&<p className="text-sm text-zinc-400">No uploads yet. <Link className="text-violet-300" to="/upload">Upload your first note →</Link></p>}</div></div>}

const nav=[['/','Dashboard',LayoutDashboard],['/explore','Explore Notes',Compass],['/search','Semantic Search',Sparkles],['/upload','Upload Notes',Upload],['/pyqs','PYQs',FileQuestion],['/exam','Exam Mode',Target],['/ai','Pragya AI',Bot],['/graph','Knowledge Graph',Network],['/saved','Saved',Bookmark],['/my','My Notes',FileText],['/request','Request a Note',HandHelping],['/profile','Profile',User]]
function Shell(){return <div className="min-h-screen md:flex"><aside className="md:w-56 md:min-h-screen md:sticky md:top-0 md:h-screen border-b md:border-r border-white/10 p-3 shrink-0 bg-black/40"><div className="hidden md:flex items-center gap-2 px-2 mb-5"><div className="size-8 rounded-lg bg-violet-600 grid place-items-center"><GraduationCap size={16}/></div><b>Pragya</b></div><nav className="flex md:flex-col gap-1 overflow-x-auto">{nav.map(([to,l,I])=><NavLink key={to} to={to} end={to==='/'} className={({isActive})=>'flex items-center gap-2 whitespace-nowrap rounded-xl px-3 py-2 text-sm '+(isActive?'bg-violet-600/20 text-violet-300':'text-zinc-400 hover:bg-white/5')}><I size={16}/>{l}</NavLink>)}</nav></aside>
<div className="flex-1 min-w-0"><header className="flex items-center gap-3 p-3 border-b border-white/10"><Link to="/search" className="flex-1 flex items-center gap-2 rounded-xl bg-white/5 px-3 py-2 text-sm text-zinc-400"><Search size={15}/>Search anything you need to learn…</Link><Bell size={18} className="text-zinc-400"/><div className="size-8 rounded-full bg-violet-600 grid place-items-center text-sm">P</div></header>
<main className="p-4 md:p-6 max-w-6xl"><Routes><Route path="/" element={<Dashboard/>}/><Route path="/explore" element={<Explore/>}/><Route path="/search" element={<SearchPg/>}/><Route path="/note/:id" element={<NoteDetail/>}/><Route path="/upload" element={<UploadPg/>}/><Route path="/pyqs" element={<PYQ/>}/><Route path="/exam" element={<Exam/>}/><Route path="/ai" element={<Assistant/>}/><Route path="/graph" element={<Graph/>}/><Route path="/my" element={<MyNotes/>}/><Route path="/saved" element={<Saved/>}/><Route path="/request" element={<Request/>}/><Route path="/profile" element={<Profile/>}/></Routes></main></div></div>}

export default function App(){const [auth,setAuth]=useState(false);const [saved,setSaved]=useState([1]);const [helpful,setHelpful]=useState(142);const [uploads,setUploads]=useState(0);const [,tick]=useState(0)
const reload=()=>api.boot().then(d=>{if(!d)return;notes.splice(0,notes.length,...d.notes);setSaved(d.saved);setHelpful(d.helpful);setUploads(d.uploads);tick(x=>x+1)})
useEffect(()=>{reload()},[])
const v={saved,helpful,uploads,toggleSave:id=>{setSaved(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);api.save(id)},voteHelpful:()=>{setHelpful(h=>h+1);api.helpful()},reload}
return <Ctx.Provider value={v}>{auth?<HashRouter><Shell/></HashRouter>:<Login go={()=>setAuth(true)}/>}</Ctx.Provider>}
