// Mock data layer — swap these for fetch() calls to Express/PostgreSQL later.
export const subjects=['Object Oriented Programming','Data Structures','Fundamentals of AI','Database Management Systems']
export const units={ 'Object Oriented Programming':['Unit 1: Intro to OOP','Unit 2: Classes & Constructors','Unit 3: Inheritance & Polymorphism','Unit 4: Exception Handling'],'Data Structures':['Unit 1: Arrays & Linked Lists','Unit 2: Stacks & Queues','Unit 3: Trees'],'Fundamentals of AI':['Unit 1: Intelligent Agents','Unit 2: Search Strategies'],'Database Management Systems':['Unit 1: ER Model','Unit 3: Normalization','Unit 4: Transactions & Concurrency']}
export const notes=[
{id:1,title:'Polymorphism & Inheritance — Complete Notes',subj:'Object Oriented Programming',unit:'Unit 3',topic:'Polymorphism',by:'Ananya Sharma',helpful:94,views:2314,type:'Study Notes',verified:true,kw:'polymorphism overriding overloading java example inheritance runtime compile'},
{id:2,title:'Runtime Polymorphism — PYQ Solutions',subj:'Object Oriented Programming',unit:'Unit 3',topic:'Polymorphism',by:'Rohan Patil',helpful:91,views:1580,type:'PYQ',verified:true,kw:'polymorphism runtime pyq exam dynamic dispatch java'},
{id:3,title:'Method Overriding — Revision Sheet',subj:'Object Oriented Programming',unit:'Unit 3',topic:'Method Overriding',by:'Sneha Kulkarni',helpful:87,views:960,type:'Handwritten',verified:false,kw:'overriding super method override revision java'},
{id:4,title:'Exception Handling — try/catch/finally',subj:'Object Oriented Programming',unit:'Unit 4',topic:'Exception Handling',by:'Faculty: Prof. Joshi',helpful:92,views:1210,type:'Faculty Material',verified:true,kw:'exception try catch finally throw custom errors'},
{id:5,title:'Binary Trees & Traversals',subj:'Data Structures',unit:'Unit 3',topic:'Trees',by:'Ananya Sharma',helpful:89,views:1745,type:'Study Notes',verified:true,kw:'tree binary inorder preorder postorder traversal bst'},
{id:6,title:'Normalization 1NF–BCNF Made Simple',subj:'Database Management Systems',unit:'Unit 3',topic:'Normalization',by:'Aditya Deshmukh',helpful:90,views:2080,type:'Study Notes',verified:true,kw:'normalization 1nf 2nf 3nf bcnf functional dependency database'},
{id:7,title:'A* and BFS/DFS Search Strategies',subj:'Fundamentals of AI',unit:'Unit 2',topic:'Search',by:'Meera Iyer',helpful:85,views:870,type:'Study Notes',verified:false,kw:'search astar heuristic bfs dfs agent ai'}]
export const pyqs=[{topic:'Polymorphism',q:'Explain runtime polymorphism with suitable example.',asked:[['2025',8],['2024',6],['2023',8]]},{topic:'Inheritance',q:'Differentiate single and multilevel inheritance in Java.',asked:[['2025',6],['2023',6]]},{topic:'Exception Handling',q:'Explain try, catch, finally with a program.',asked:[['2024',8],['2022',6]]}]
export const ai={summary:'Polymorphism lets one interface represent many forms. Compile-time polymorphism (overloading) is resolved by the compiler; runtime polymorphism (overriding) is resolved via dynamic method dispatch based on the actual object type.',concepts:['Compile-time polymorphism','Runtime polymorphism','Method overloading','Method overriding','Dynamic method dispatch'],qs:['Explain runtime polymorphism with an example.','Differentiate overloading and overriding.','What is dynamic method dispatch?'],mcq:[{q:'Which is runtime polymorphism?',o:['Method overloading','Method overriding','Constructor chaining','Static binding'],a:1},{q:'Overloaded methods must differ in…',o:['Return type only','Parameter list','Access modifier','Class name'],a:1},{q:'Dynamic dispatch is resolved at…',o:['Compile time','Load time','Run time','Link time'],a:2}]}
export const replies={inherit:'Inheritance lets a class (child) reuse fields and methods of another (parent) using `extends`. Think: Dog extends Animal — Dog gets eat() for free and can add bark().',question:'Top OOP questions (by PYQ frequency): 1) Runtime polymorphism (asked 3/3 years) 2) Inheritance types 3) Exception handling with finally.',plan:'2-day plan — Day 1: Polymorphism, Inheritance notes + PYQs. Day 2: Exception handling, MCQ quiz, mock test.',note:'This note (Polymorphism & Inheritance) covers overloading vs overriding with Java examples. Want the summary or MCQs?',def:'I matched your question to Unit 3 notes and PYQs. Try asking about inheritance, important questions, or a revision plan.'}
